spec:
  template:
    spec:
      containers:
        - env:
          - name: GREETING_PREFIX
            valueFrom:
             configMapKeyRef:
                name: minishift-configmaps
                key: greeter.prefix
          volumeMounts:
          - name: application-config
            mountPath: "/deployments/config"
            readOnly: true
      volumes:
      - name: application-config
        configMap:
          name: spring-app-config
          items:
          - key: application.yml
            path: application.yml