server:
  port: 9999

greeter.message: Spring Boot application.yml has been mounted as volume on Kubernetes!

app:
  test: hello world
  people:
    -
      firstName: suhael
      lastName: akhtar
    -
      firstName: eesa
      lastName: akhtar
    -
      firstName: ameera
      lastName: akhtar