server:
  port: 9999

greeter.message: This is reading from config map - no need for fabric 8
greeter.prefix: ${GREETING_PREFIX}

app:
  test: hello world
  people:
    -
      firstName: suhael
      lastName: akhtar
    -
      firstName: eesa
      lastName: akhtar
    -
      firstName: ameera
      lastName: akhtar